// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: io.whiteley.ATlas.pin

package models

import (
	"fmt"
	"io"

	lexutil "github.com/bluesky-social/indigo/lex/util"
	cid "github.com/ipfs/go-cid"
	cbg "github.com/whyrusleeping/cbor-gen"
	xerrors "golang.org/x/xerrors"
)

func init() {
	lexutil.RegisterType("io.whiteley.ATlas.pin", &AtlasPinRecord{})
}

type AtlasPinRecord struct {
	LexiconTypeID string  `json:"$type" cborgen:"$type,const=io.whiteley.ATlas.pin"`
	Description   string  `json:"description" cborgen:"description"`
	Did           string  `json:"did" cborgen:"did"`
	Latitude      string  `json:"latitude" cborgen:"latitude"`
	Longitude     string  `json:"longitude" cborgen:"longitude"`
	PlacedAt      string  `json:"placedAt" cborgen:"placedAt"`
	Website       *string `json:"website,omitempty" cborgen:"website,omitempty"`
}

// Below was generated and copied over from the bluesky-social/indigo repo
// See https://github.com/bluesky-social/indigo/blob/78a1c1894f36ada211de6d075b63d9ade083b49e/HACKING.md#lexicon-and-cbor-code-generation
func (t *AtlasPinRecord) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)
	fieldCount := 7

	if t.Website == nil {
		fieldCount--
	}

	if _, err := cw.Write(cbg.CborEncodeMajorType(cbg.MajMap, uint64(fieldCount))); err != nil {
		return err
	}

	// t.Did (string) (string)
	if len("did") > 1000000 {
		return xerrors.Errorf("Value in field \"did\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("did"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("did")); err != nil {
		return err
	}

	if len(t.Did) > 1000000 {
		return xerrors.Errorf("Value in field t.Did was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(t.Did))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string(t.Did)); err != nil {
		return err
	}

	// t.LexiconTypeID (string) (string)
	if len("$type") > 1000000 {
		return xerrors.Errorf("Value in field \"$type\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("$type"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("$type")); err != nil {
		return err
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("io.whiteley.ATlas.pin"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("io.whiteley.ATlas.pin")); err != nil {
		return err
	}

	// t.Website (string) (string)
	if t.Website != nil {

		if len("website") > 1000000 {
			return xerrors.Errorf("Value in field \"website\" was too long")
		}

		if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("website"))); err != nil {
			return err
		}
		if _, err := cw.WriteString(string("website")); err != nil {
			return err
		}

		if t.Website == nil {
			if _, err := cw.Write(cbg.CborNull); err != nil {
				return err
			}
		} else {
			if len(*t.Website) > 1000000 {
				return xerrors.Errorf("Value in field t.Website was too long")
			}

			if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(*t.Website))); err != nil {
				return err
			}
			if _, err := cw.WriteString(string(*t.Website)); err != nil {
				return err
			}
		}
	}

	// t.Latitude (string) (string)
	if len("latitude") > 1000000 {
		return xerrors.Errorf("Value in field \"latitude\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("latitude"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("latitude")); err != nil {
		return err
	}

	if len(t.Latitude) > 1000000 {
		return xerrors.Errorf("Value in field t.Latitude was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(t.Latitude))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string(t.Latitude)); err != nil {
		return err
	}

	// t.PlacedAt (string) (string)
	if len("placedAt") > 1000000 {
		return xerrors.Errorf("Value in field \"placedAt\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("placedAt"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("placedAt")); err != nil {
		return err
	}

	if len(t.PlacedAt) > 1000000 {
		return xerrors.Errorf("Value in field t.PlacedAt was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(t.PlacedAt))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string(t.PlacedAt)); err != nil {
		return err
	}

	// t.Longitude (string) (string)
	if len("longitude") > 1000000 {
		return xerrors.Errorf("Value in field \"longitude\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("longitude"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("longitude")); err != nil {
		return err
	}

	if len(t.Longitude) > 1000000 {
		return xerrors.Errorf("Value in field t.Longitude was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(t.Longitude))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string(t.Longitude)); err != nil {
		return err
	}

	// t.Description (string) (string)
	if len("description") > 1000000 {
		return xerrors.Errorf("Value in field \"description\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("description"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("description")); err != nil {
		return err
	}

	if len(t.Description) > 1000000 {
		return xerrors.Errorf("Value in field t.Description was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(t.Description))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string(t.Description)); err != nil {
		return err
	}
	return nil
}

func (t *AtlasPinRecord) UnmarshalCBOR(r io.Reader) (err error) {
	*t = AtlasPinRecord{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("AtlasPinRecord: map struct too large (%d)", extra)
	}

	n := extra

	nameBuf := make([]byte, 11)
	for i := uint64(0); i < n; i++ {
		nameLen, ok, err := cbg.ReadFullStringIntoBuf(cr, nameBuf, 1000000)
		if err != nil {
			return err
		}

		if !ok {
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(cr, func(cid.Cid) {}); err != nil {
				return err
			}
			continue
		}

		switch string(nameBuf[:nameLen]) {
		// t.Did (string) (string)
		case "did":

			{
				sval, err := cbg.ReadStringWithMax(cr, 1000000)
				if err != nil {
					return err
				}

				t.Did = string(sval)
			}
			// t.LexiconTypeID (string) (string)
		case "$type":

			{
				sval, err := cbg.ReadStringWithMax(cr, 1000000)
				if err != nil {
					return err
				}

				t.LexiconTypeID = string(sval)
			}
			// t.Website (string) (string)
		case "website":

			{
				b, err := cr.ReadByte()
				if err != nil {
					return err
				}
				if b != cbg.CborNull[0] {
					if err := cr.UnreadByte(); err != nil {
						return err
					}

					sval, err := cbg.ReadStringWithMax(cr, 1000000)
					if err != nil {
						return err
					}

					t.Website = (*string)(&sval)
				}
			}
			// t.Latitude (string) (string)
		case "latitude":

			{
				sval, err := cbg.ReadStringWithMax(cr, 1000000)
				if err != nil {
					return err
				}

				t.Latitude = string(sval)
			}
			// t.PlacedAt (string) (string)
		case "placedAt":

			{
				sval, err := cbg.ReadStringWithMax(cr, 1000000)
				if err != nil {
					return err
				}

				t.PlacedAt = string(sval)
			}
			// t.Longitude (string) (string)
		case "longitude":

			{
				sval, err := cbg.ReadStringWithMax(cr, 1000000)
				if err != nil {
					return err
				}

				t.Longitude = string(sval)
			}
			// t.Description (string) (string)
		case "description":

			{
				sval, err := cbg.ReadStringWithMax(cr, 1000000)
				if err != nil {
					return err
				}

				t.Description = string(sval)
			}

		default:
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(r, func(cid.Cid) {}); err != nil {
				return err
			}
		}
	}

	return nil
}
